# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CARIRTcpp <- function(ConnectMatrix, VoteMatrix, nonUnanimous, InitialAveragePrefs, InitialAlphas, InitialBetas, SaveChains, BurntIterations, SavedIterations, ThinningFactor) {
    .Call('eliot_CARIRTcpp', PACKAGE = 'eliot', ConnectMatrix, VoteMatrix, nonUnanimous, InitialAveragePrefs, InitialAlphas, InitialBetas, SaveChains, BurntIterations, SavedIterations, ThinningFactor)
}

LDAIRTcpp <- function(WordMatrixDocs, WordMatrixTerms, WordMatrixCounts, VoteMatrix, LDAtopics, LDAterms, LDAwords, LDAdocterms, LDAalpha, LDAbeta, IRTprec, StartIdealPoints, SaveChains, BurntIterations, SavedIterations) {
    .Call('eliot_LDAIRTcpp', PACKAGE = 'eliot', WordMatrixDocs, WordMatrixTerms, WordMatrixCounts, VoteMatrix, LDAtopics, LDAterms, LDAwords, LDAdocterms, LDAalpha, LDAbeta, IRTprec, StartIdealPoints, SaveChains, BurntIterations, SavedIterations)
}

LIRTcpp <- function(LambdaMatrix, VoteMatrix, IRTprec, StartIdealPoints, SaveChains, BurntIterations, SavedIterations) {
    .Call('eliot_LIRTcpp', PACKAGE = 'eliot', LambdaMatrix, VoteMatrix, IRTprec, StartIdealPoints, SaveChains, BurntIterations, SavedIterations)
}

wordfishcpp <- function(wfm, dir, priors, tol) {
    .Call('eliot_wordfishcpp', PACKAGE = 'eliot', wfm, dir, priors, tol)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('eliot_RcppExport_registerCCallable', PACKAGE = 'eliot')
})
